###
POST http://localhost:3000/book HTTP/1.1
Content-Type: application/json

{
    "name": "El eterno resplandor de una mente sin recuerdos",
    "autor": "Saul",
    "estado": true
}

###
GET http://localhost:3000/book HTTP/1.1
Content-Type: application/json

{
    "name": "El eterno resplandor de una Mente sin recuerdos"
}