###
GET http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "id": 1
}

###
GET http://localhost:3000/user/all HTTP/1.1

###
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json 

{
    "name": "Jal",
    "last_name": "Mai",
    "numero_telefono": "9671941293"
}